#!/bin/bash
# ImageHost Interactive Setup Script
# This script guides you through setting up the ImageHost platform

set -e

echo "========================================="
echo "  ImageHost Setup Script"
echo "========================================="
echo ""

# Check prerequisites
check_prerequisites() {
    echo "Checking prerequisites..."
    
    if ! command -v docker &> /dev/null; then
        echo "❌ Docker is not installed"
        echo "   Please install Docker from https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        echo "❌ Docker Compose is not installed"
        echo "   Please install Docker Compose from https://docs.docker.com/compose/install/"
        exit 1
    fi
    
    echo "✅ Docker and Docker Compose found"
    echo ""
}

# Get user input
get_server_config() {
    echo "Server Configuration"
    echo "--------------------"
    
    read -p "Enter server IP address (press Enter for auto-detect): " SERVER_IP
    
    if [ -z "$SERVER_IP" ]; then
        SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "127.0.0.1")
        echo "Auto-detected IP: $SERVER_IP"
    fi
    
    read -p "Enter domain name (press Enter for 'localhost'): " DOMAIN
    
    if [ -z "$DOMAIN" ]; then
        DOMAIN="localhost"
    fi
    
    echo ""
    echo "Configuration:"
    echo "  IP Address: $SERVER_IP"
    echo "  Domain: $DOMAIN"
    echo ""
}

# Generate secure secrets
generate_secrets() {
    echo "Generating JWT secrets..."
    
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
    JWT_REFRESH_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
    POSTGRES_PASSWORD=$(openssl rand -base64 16 2>/dev/null || head -c 16 /dev/urandom | base64)
    
    echo "✅ Secrets generated"
    echo ""
}

# Create .env file
create_env_file() {
    echo "Creating .env file..."
    
    cat > .env << EOF
# ImageHost Environment Configuration
# Generated by setup script on $(date)

# Application
NODE_ENV=production
PORT=5000

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=imagehost
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/imagehost

# Redis
REDIS_URL=redis://localhost:6379

# JWT Secrets
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# File Upload Configuration
UPLOAD_PATH=/app/uploads
UPLOAD_MAX_SIZE=20971520
UPLOAD_ALLOWED_FORMATS=jpg,jpeg,png,gif,webp

# Security Settings
BCRYPT_ROUNDS=12
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
BRUTEFORCE_MAX_ATTEMPTS=5
BRUTEFORCE_WINDOW_MS=900000

# Registration
REGISTRATION_ENABLED=false

# Frontend URLs
NEXT_PUBLIC_API_URL=http://${SERVER_IP}:5000/api
NEXT_PUBLIC_NGINX_URL=http://${DOMAIN}

# Admin default password (CHANGE ME!)
# Default admin: admin@imagehost.local
EOF

    echo "✅ .env file created"
    echo ""
}

# Create docker-entrypoint.sh for backend
create_docker_entrypoints() {
    echo "Creating Docker entrypoint scripts..."
    
    # Backend entrypoint
    cat > docker-entrypoint.sh << 'EOF'
#!/bin/bash
set -e

echo "Starting ImageHost Backend..."

# Wait for database
for i in {1..30}; do
  if pg_isready -h postgres -U postgres -d imagehost 2>/dev/null; then
    echo "Database is ready!"
    break
  fi
  echo "Waiting for database..."
  sleep 1
done

# Run migrations and seed
cd /app
if [ -f "prisma/schema.prisma" ]; then
  echo "Generating Prisma client..."
  npx prisma generate || true
  
  echo "Running migrations..."
  npx prisma migrate deploy || npx prisma db push || true
  
  echo "Seeding database..."
  npx tsx prisma/seed.ts 2>/dev/null || node prisma/seed.js 2>/dev/null || true
fi

exec "$@"
EOF

    chmod +x docker-entrypoint.sh

    # Frontend entrypoint
    cat > docker-entrypoint-frontend.sh << 'EOF'
#!/bin/bash
set -e

echo "Starting ImageHost Frontend..."

# Build settings (for SSR)
export NEXT_TELEMETRY_DISABLED=1

exec "$@"
EOF

    chmod +x docker-entrypoint-frontend.sh

    echo "✅ Entrypoint scripts created"
    echo ""
}

# Update nginx config
update_nginx() {
    echo "Checking nginx configuration..."
    
    if [ -f "nginx/nginx.conf" ]; then
        # Create conf.d directory if it doesn't exist
        mkdir -p nginx/conf.d
        
        echo "✅ Nginx configuration ready"
    else
        echo "⚠️  Nginx config not found - skipping"
    fi
    echo ""
}

# Show deployment instructions
show_instructions() {
    echo "========================================="
    echo "  Setup Complete!"
    echo "========================================="
    echo ""
    echo "To start the application:"
    echo "  docker-compose up -d"
    echo ""
    echo "Access points:"
    echo "  Frontend: http://${DOMAIN}:3000"
    echo "  API:      http://${DOMAIN}:5000/api"
    echo ""
    echo "Default Admin Credentials:"
    echo "  Email:    admin@imagehost.local"
    echo "  Password: Admin123!@#"
    echo ""
    echo "IMPORTANT: Change the admin password immediately!"
    echo ""
    echo "Database connection:"
    echo "  Host: localhost"
    echo "  Port: 5432"
    echo "  DB:   imagehost"
    echo "  User: postgres"
    echo "  Password: ${POSTGRES_PASSWORD}"
    echo ""
}

# Main execution
main() {
    check_prerequisites
    get_server_config
    generate_secrets
    create_env_file
    create_docker_entrypoints
    update_nginx
    show_instructions
}

main "$@"