<# 
.SYNOPSIS
    ImageHost Setup Script for Windows

.DESCRIPTION
    This script guides you through setting up the ImageHost platform.
    It will ask for IP address and domain, then generate all necessary files.

.NOTES
    Requires: Docker Desktop, PowerShell 5.1+
#>

$ErrorActionPreference = "Stop"

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  ImageHost Setup Script" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""

# Check prerequisites
Write-Host "Checking prerequisites..." -ForegroundColor Yellow
$dockerExists = Get-Command docker -ErrorAction SilentlyContinue
$composeExists = Get-Command docker-compose -ErrorAction SilentlyContinue -or (docker compose version -ErrorAction SilentlyContinue)

if (-not $dockerExists) {
    Write-Host "❌ Docker is not installed" -ForegroundColor Red
    Write-Host "   Please install Docker Desktop from https://www.docker.com/products/docker-desktop/" -ForegroundColor Red
    exit 1
}

if (-not $composeExists) {
    Write-Host "❌ Docker Compose is not installed" -ForegroundColor Red
    Write-Host "   Included with Docker Desktop" -ForegroundColor Red
    exit 1
}

Write-Host "✅ Docker and Docker Compose found" -ForegroundColor Green
Write-Host ""

# Get server IP
Write-Host "Server Configuration" -ForegroundColor Cyan
Write-Host "--------------------" -ForegroundColor Cyan

$SERVER_IP = Read-Host "Enter server IP address (press Enter for auto-detect)"
if (-not $SERVER_IP) {
    try {
        $SERVER_IP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.PrefixOrigin -ne "WellKnown" -and $_.IPAddress -ne "127.0.0.1"} | Select-Object -First 1).IPAddress
    } catch {
        $SERVER_IP = "127.0.0.1"
    }
    Write-Host "Auto-detected IP: $SERVER_IP" -ForegroundColor Green
}

$DOMAIN = Read-Host "Enter domain name (press Enter for 'localhost')"
if (-not $DOMAIN) {
    $DOMAIN = "localhost"
}

Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  IP Address: $SERVER_IP" -ForegroundColor White
Write-Host "  Domain: $DOMAIN" -ForegroundColor White
Write-Host ""

# Generate secrets
Write-Host "Generating JWT secrets..." -ForegroundColor Yellow
$JWT_SECRET = [System.Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }))
$JWT_REFRESH_SECRET = [System.Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }))
$POSTGRES_PASSWORD = [System.Convert]::ToBase64String((1..16 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }))
Write-Host "✅ Secrets generated" -ForegroundColor Green
Write-Host ""

# Create .env file
Write-Host "Creating .env file..." -ForegroundColor Yellow
$envContent = @"
# ImageHost Environment Configuration
# Generated by setup script on $(Get-Date)

# Application
NODE_ENV=production
PORT=5000

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=imagehost
DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@localhost:5432/imagehost

# Redis
REDIS_URL=redis://localhost:6379

# JWT Secrets
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# File Upload Configuration
UPLOAD_PATH=/app/uploads
UPLOAD_MAX_SIZE=20971520
UPLOAD_ALLOWED_FORMATS=jpg,jpeg,png,gif,webp

# Security Settings
BCRYPT_ROUNDS=12
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100
BRUTEFORCE_MAX_ATTEMPTS=5
BRUTEFORCE_WINDOW_MS=900000

# Registration
REGISTRATION_ENABLED=false

# Frontend URLs
NEXT_PUBLIC_API_URL=http://$SERVER_IP:5000/api
NEXT_PUBLIC_NGINX_URL=http://$DOMAIN

# Admin default password (CHANGE ME!)
# Default admin: admin@imagehost.local
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8
Write-Host "✅ .env file created" -ForegroundColor Green
Write-Host ""

# Create docker-entrypoint.sh
$backendEntrypoint = @"
#!/bin/bash
set -e

echo "Starting ImageHost Backend..."

# Wait for database
for i in {1..30}; do
  if pg_isready -h postgres -U postgres -d imagehost 2>/dev/null; then
    echo "Database is ready!"
    break
  fi
  echo "Waiting for database..."
  sleep 1
done

# Run migrations and seed
cd /app
if [ -f "prisma/schema.prisma" ]; then
  echo "Generating Prisma client..."
  npx prisma generate || true
  
  echo "Running migrations..."
  npx prisma migrate deploy || npx prisma db push || true
  
  echo "Seeding database..."
  npx tsx prisma/seed.ts 2>/dev/null || node prisma/seed.js 2>/dev/null || true
fi

exec "\$@"
"@

$backendEntrypoint | Out-File -FilePath "docker-entrypoint.sh" -Encoding utf8

$frontendEntrypoint = @"
#!/bin/bash
set -e

echo "Starting ImageHost Frontend..."

# Build settings (for SSR)
export NEXT_TELEMETRY_DISABLED=1

exec "\$@"
"@

$frontendEntrypoint | Out-File -FilePath "docker-entrypoint-frontend.sh" -Encoding utf8

Write-Host "✅ Entrypoint scripts created" -ForegroundColor Green
Write-Host ""

# Show instructions
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  Setup Complete!" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "To start the application:" -ForegroundColor Yellow
Write-Host "  docker-compose up -d" -ForegroundColor White
Write-Host ""
Write-Host "Access points:" -ForegroundColor Yellow
Write-Host "  Frontend: http://$DOMAIN:3000" -ForegroundColor White
Write-Host "  API:      http://$DOMAIN:5000/api" -ForegroundColor White
Write-Host ""
Write-Host "Default Admin Credentials:" -ForegroundColor Yellow
Write-Host "  Email:    admin@imagehost.local" -ForegroundColor White
Write-Host "  Password: Admin123!@#" -ForegroundColor White
Write-Host ""
Write-Host "IMPORTANT: Change the admin password immediately!" -ForegroundColor Red
Write-Host ""
Write-Host "Database connection:" -ForegroundColor Yellow
Write-Host "  Host: localhost" -ForegroundColor White
Write-Host "  Port: 5432" -ForegroundColor White
Write-Host "  DB:   imagehost" -ForegroundColor White
Write-Host "  User: postgres" -ForegroundColor White
Write-Host "  Password: $POSTGRES_PASSWORD" -ForegroundColor White